name: CSDA Version
description: Calculate the next CSDA version for this repository
branding:
  icon: radio
  color: blue

outputs:
  version:
    description: The next CSDA version
    value: ${{ steps.calculate.outputs.version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install
      shell: bash
      run: python -m pip install .
    - name: Fetch tags
      shell: bash
      run: git fetch --tags
    - name: Get last tag
      shell: bash
      id: last-tag
      run: |
        LAST_TAG=$(git tag --list 'v*.*.*' --sort=-version:refname | head -n 1)
        echo "tag=$LAST_TAG" >> "$GITHUB_OUTPUT"
    - name: Fetch csda-version.txt
      shell: bash
      id: csda-version
      run: |
        CSDA_VERSION=$(curl -s https://raw.githubusercontent.com/gadomski/csda-version/refs/heads/main/csda-version.txt | tr -d '[:space:]')
        echo "version=$CSDA_VERSION" >> "$GITHUB_OUTPUT"
    - id: calculate
      shell: bash
      run: csda-version next-version "${{ steps.csda-version.outputs.version }}" "${{ steps.last-tag.outputs.tag }}"
